-- =========================================================================
-- Project: Running Coach (러닝 코치)
-- Target DBMS: Oracle Database 12c or higher
-- Version: v1.2 (Based on Usecase Specs v1.2 & Table Specs v1.1/Index Specs v1.2)
-- Description: Oracle Database DDL & Initial Common Code Data Seed Script
-- Created Date: 2026-06-24
-- Writer: Running Coach DB Design Team
-- =========================================================================

-- ==========================================
-- 0. DROP TABLES (CASCADE CONSTRAINTS)
-- ==========================================
DROP TABLE RUN_RECORD CASCADE CONSTRAINTS;
DROP TABLE GOAL CASCADE CONSTRAINTS;
DROP TABLE RACE_RECORD CASCADE CONSTRAINTS;
DROP TABLE RUNNER_SOCIAL_ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE RUNNER CASCADE CONSTRAINTS;
DROP TABLE CODE_DETAIL CASCADE CONSTRAINTS;
DROP TABLE CODE_GROUP CASCADE CONSTRAINTS;

-- ==========================================
-- 1. CREATE TABLES & PRIMARY KEYS
-- ==========================================

-- 1-1. CODE_GROUP (코드 그룹)
CREATE TABLE CODE_GROUP (
    group_code  VARCHAR2(30) NOT NULL,
    group_name  VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    use_yn      CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at  TIMESTAMP,
    CONSTRAINT PK_CODE_GROUP PRIMARY KEY (group_code),
    CONSTRAINT CK_CODE_GROUP_USE_YN CHECK (use_yn IN ('Y', 'N'))
);

-- 1-2. CODE_DETAIL (코드 상세)
CREATE TABLE CODE_DETAIL (
    code_id     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_code  VARCHAR2(30) NOT NULL,
    code_value  VARCHAR2(30) NOT NULL,
    code_name   VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    sort_order  NUMBER(10),
    use_yn      CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at  TIMESTAMP,
    CONSTRAINT PK_CODE_DETAIL PRIMARY KEY (code_id),
    CONSTRAINT CK_CODE_DETAIL_USE_YN CHECK (use_yn IN ('Y', 'N'))
);

-- 1-3. RUNNER (러너 정보)
CREATE TABLE RUNNER (
    runner_id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nickname           VARCHAR2(50),
    profile_image_url  VARCHAR2(500),
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at         TIMESTAMP,
    CONSTRAINT PK_RUNNER PRIMARY KEY (runner_id)
);

-- 1-4. RUNNER_SOCIAL_ACCOUNT (소셜 로그인 정보)
CREATE TABLE RUNNER_SOCIAL_ACCOUNT (
    social_account_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    runner_id         NUMBER(19) NOT NULL,
    provider          VARCHAR2(20) NOT NULL,
    provider_user_id  VARCHAR2(100) NOT NULL,
    provider_email    VARCHAR2(200),
    is_primary        CHAR(1) DEFAULT 'N' NOT NULL,
    connected_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    last_login_at     TIMESTAMP,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at        TIMESTAMP,
    CONSTRAINT PK_RUNNER_SOCIAL_ACCOUNT PRIMARY KEY (social_account_id),
    CONSTRAINT CK_SOCIAL_IS_PRIMARY CHECK (is_primary IN ('Y', 'N'))
);

-- 1-5. RUN_RECORD (러닝 기록)
CREATE TABLE RUN_RECORD (
    run_record_id      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    runner_id          NUMBER(19) NOT NULL,
    run_datetime       TIMESTAMP NOT NULL,
    run_date           DATE NOT NULL,
    duration_sec       NUMBER(10) NOT NULL,
    distance_km        NUMBER(6,2) NOT NULL,
    avg_pace_sec       NUMBER(10),
    avg_hr             NUMBER(10),
    training_type_code VARCHAR2(30) NOT NULL,
    rpe                NUMBER(10),
    temperature        NUMBER(4,1),
    humidity           NUMBER(10),
    weather_code       VARCHAR2(30),
    memo               VARCHAR2(1000),
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at         TIMESTAMP,
    CONSTRAINT PK_RUN_RECORD PRIMARY KEY (run_record_id),
    CONSTRAINT CK_RUN_RECORD_RPE CHECK (rpe BETWEEN 1 AND 10),
    CONSTRAINT CK_RUN_DISTANCE CHECK (distance_km > 0),
    CONSTRAINT CK_RUN_DURATION CHECK (duration_sec > 0),
    CONSTRAINT CK_RUN_HR CHECK (avg_hr IS NULL OR avg_hr BETWEEN 30 AND 250)
);

-- 1-6. GOAL (목표 관리)
CREATE TABLE GOAL (
    goal_id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    runner_id        NUMBER(19) NOT NULL,
    goal_type_code   VARCHAR2(30) NOT NULL,
    goal_unit_code   VARCHAR2(30) NOT NULL,
    target_year      NUMBER(10),
    target_month     NUMBER(10),
    target_value     NUMBER(10,2) NOT NULL,
    achieved_value   NUMBER(10,2) DEFAULT 0.00 NOT NULL,
    start_date       DATE,
    end_date         DATE,
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at       TIMESTAMP,
    CONSTRAINT PK_GOAL PRIMARY KEY (goal_id),
    CONSTRAINT CK_GOAL_MONTH CHECK (target_month BETWEEN 1 AND 12)
);

-- 1-7. RACE_RECORD (대회 기록)
CREATE TABLE RACE_RECORD (
    race_record_id        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    runner_id             NUMBER(19) NOT NULL,
    race_name             VARCHAR2(200) NOT NULL,
    race_date             DATE NOT NULL,
    race_type_code        VARCHAR2(30) NOT NULL,
    record_sec            NUMBER(10) NOT NULL,
    certificate_image_url VARCHAR2(500),
    memo                  VARCHAR2(1000),
    created_at            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at            TIMESTAMP,
    CONSTRAINT PK_RACE_RECORD PRIMARY KEY (race_record_id)
);


-- ==========================================
-- 2. CREATE INDEXES (Based on Index Spec v1.2)
-- ==========================================

-- 2-1. RUNNER Indexes (No Indexes defined for RUNNER after email removal)

-- 2-2. RUNNER_SOCIAL_ACCOUNT Indexes
CREATE UNIQUE INDEX UIDX_RUNNER_SOCIAL_ACCOUNT_01 ON RUNNER_SOCIAL_ACCOUNT(provider, provider_user_id);
CREATE INDEX IDX_RUNNER_SOCIAL_ACCOUNT_01 ON RUNNER_SOCIAL_ACCOUNT(runner_id);

-- 2-3. RUN_RECORD Indexes
CREATE INDEX IDX_RUN_RECORD_01 ON RUN_RECORD(runner_id, run_date);
CREATE INDEX IDX_RUN_RECORD_02 ON RUN_RECORD(runner_id, training_type_code);
CREATE INDEX IDX_RUN_RECORD_03 ON RUN_RECORD(run_date);
CREATE INDEX IDX_RUN_RECORD_04 ON RUN_RECORD(runner_id, run_datetime);

-- 2-4. GOAL Indexes
CREATE UNIQUE INDEX UIDX_GOAL_01 ON GOAL(runner_id, target_year, target_month, goal_type_code);

-- 2-5. RACE_RECORD Indexes
CREATE INDEX IDX_RACE_RECORD_01 ON RACE_RECORD(runner_id);
CREATE INDEX IDX_RACE_RECORD_02 ON RACE_RECORD(runner_id, race_type_code);

-- 2-6. CODE_DETAIL Indexes
CREATE UNIQUE INDEX UIDX_CODE_DETAIL_01 ON CODE_DETAIL(group_code, code_value);
CREATE INDEX IDX_CODE_DETAIL_02 ON CODE_DETAIL(group_code);


-- ==========================================
-- 3. CREATE UNIQUE & FOREIGN KEY CONSTRAINTS
-- ==========================================

-- 3-1. UNIQUE CONSTRAINTS (Using pre-created Unique Indexes)
ALTER TABLE RUNNER_SOCIAL_ACCOUNT ADD CONSTRAINT UQ_SOCIAL_PROVIDER_USER UNIQUE (provider, provider_user_id) USING INDEX UIDX_RUNNER_SOCIAL_ACCOUNT_01;
ALTER TABLE GOAL ADD CONSTRAINT UQ_GOAL_RUNNER_MONTH UNIQUE (runner_id, target_year, target_month, goal_type_code) USING INDEX UIDX_GOAL_01;
ALTER TABLE CODE_DETAIL ADD CONSTRAINT UQ_CODE_DETAIL_VAL UNIQUE (group_code, code_value) USING INDEX UIDX_CODE_DETAIL_01;

-- 3-2. FOREIGN KEY CONSTRAINTS
ALTER TABLE CODE_DETAIL ADD CONSTRAINT FK_CODE_DETAIL_GROUP FOREIGN KEY (group_code) REFERENCES CODE_GROUP(group_code) ON DELETE CASCADE;
ALTER TABLE RUNNER_SOCIAL_ACCOUNT ADD CONSTRAINT FK_SOCIAL_RUNNER FOREIGN KEY (runner_id) REFERENCES RUNNER(runner_id) ON DELETE CASCADE;
ALTER TABLE RUN_RECORD ADD CONSTRAINT FK_RUN_RECORD_RUNNER FOREIGN KEY (runner_id) REFERENCES RUNNER(runner_id) ON DELETE CASCADE;
ALTER TABLE GOAL ADD CONSTRAINT FK_GOAL_RUNNER FOREIGN KEY (runner_id) REFERENCES RUNNER(runner_id) ON DELETE CASCADE;
ALTER TABLE RACE_RECORD ADD CONSTRAINT FK_RACE_RECORD_RUNNER FOREIGN KEY (runner_id) REFERENCES RUNNER(runner_id) ON DELETE CASCADE;


-- ==========================================
-- 4. SCHEMA COMMENTS (Table & Column Commenting)
-- ==========================================

-- 4-1. CODE_GROUP Comments
COMMENT ON TABLE CODE_GROUP IS '공통 코드 그룹 테이블';
COMMENT ON COLUMN CODE_GROUP.group_code IS '그룹 코드 식별자 (예: TRAINING_TYPE, WEATHER_TYPE 등)';
COMMENT ON COLUMN CODE_GROUP.group_name IS '그룹명 (한글명)';
COMMENT ON COLUMN CODE_GROUP.description IS '그룹 설명';
COMMENT ON COLUMN CODE_GROUP.use_yn IS '사용 여부 (Y/N)';
COMMENT ON COLUMN CODE_GROUP.created_at IS '최초 생성 일시';
COMMENT ON COLUMN CODE_GROUP.updated_at IS '최종 수정 일시';

-- 4-2. CODE_DETAIL Comments
COMMENT ON TABLE CODE_DETAIL IS '공통 코드 상세 매핑 테이블';
COMMENT ON COLUMN CODE_DETAIL.code_id IS '상세 코드 ID (PK)';
COMMENT ON COLUMN CODE_DETAIL.group_code IS '부모 그룹 코드 (FK)';
COMMENT ON COLUMN CODE_DETAIL.code_value IS '코드값 (예: LSD, SUNNY 등)';
COMMENT ON COLUMN CODE_DETAIL.code_name IS '코드명 (한글명, 예: 장거리 지속주, 맑음 등)';
COMMENT ON COLUMN CODE_DETAIL.description IS '상세 설명';
COMMENT ON COLUMN CODE_DETAIL.sort_order IS '정렬 순서';
COMMENT ON COLUMN CODE_DETAIL.use_yn IS '사용 여부 (Y/N)';
COMMENT ON COLUMN CODE_DETAIL.created_at IS '최초 생성 일시';
COMMENT ON COLUMN CODE_DETAIL.updated_at IS '최종 수정 일시';

-- 4-3. RUNNER Comments
COMMENT ON TABLE RUNNER IS '러너 기본 정보 테이블';
COMMENT ON COLUMN RUNNER.runner_id IS '러너 고유 식별 ID (PK)';
COMMENT ON COLUMN RUNNER.nickname IS '사용자 닉네임';
COMMENT ON COLUMN RUNNER.profile_image_url IS '소셜 연동 프로필 이미지 경로';
COMMENT ON COLUMN RUNNER.created_at IS '회원 가입 일시';
COMMENT ON COLUMN RUNNER.updated_at IS '회원 정보 수정 일시';

-- 4-4. RUNNER_SOCIAL_ACCOUNT Comments
COMMENT ON TABLE RUNNER_SOCIAL_ACCOUNT IS '소셜 연동 다중 계정 정보';
COMMENT ON COLUMN RUNNER_SOCIAL_ACCOUNT.social_account_id IS '소셜 계정 ID (PK)';
COMMENT ON COLUMN RUNNER_SOCIAL_ACCOUNT.runner_id IS '소유 러너 ID (FK)';
COMMENT ON COLUMN RUNNER_SOCIAL_ACCOUNT.provider IS '소셜 서비스 제공자 (GOOGLE, NAVER 등)';
COMMENT ON COLUMN RUNNER_SOCIAL_ACCOUNT.provider_user_id IS '제공자 측 고유 사용자 식별 ID';
COMMENT ON COLUMN RUNNER_SOCIAL_ACCOUNT.provider_email IS '소셜 계정 등록 이메일';
COMMENT ON COLUMN RUNNER_SOCIAL_ACCOUNT.is_primary IS '대표 계정 여부 (Y/N)';
COMMENT ON COLUMN RUNNER_SOCIAL_ACCOUNT.connected_at IS '연동 완료 일시';
COMMENT ON COLUMN RUNNER_SOCIAL_ACCOUNT.last_login_at IS '해당 소셜 최근 로그인 일시';
COMMENT ON COLUMN RUNNER_SOCIAL_ACCOUNT.created_at IS '계정 생성 일시';
COMMENT ON COLUMN RUNNER_SOCIAL_ACCOUNT.updated_at IS '계정 변경 일시';

-- 4-5. RUN_RECORD Comments
COMMENT ON TABLE RUN_RECORD IS '러닝 기록 세부 데이터';
COMMENT ON COLUMN RUN_RECORD.run_record_id IS '기록 ID (PK)';
COMMENT ON COLUMN RUN_RECORD.runner_id IS '기록 등록 러너 ID (FK)';
COMMENT ON COLUMN RUN_RECORD.run_datetime IS '운동 시간 및 시각 (초 단위 포함)';
COMMENT ON COLUMN RUN_RECORD.run_date IS '운동 수행 일자 (필터용)';
COMMENT ON COLUMN RUN_RECORD.duration_sec IS '주행 시간 (단위: 초)';
COMMENT ON COLUMN RUN_RECORD.distance_km IS '주행 거리 (단위: km)';
COMMENT ON COLUMN RUN_RECORD.avg_pace_sec IS '평균 페이스 (단위: 초/km)';
COMMENT ON COLUMN RUN_RECORD.avg_hr IS '평균 심박수 (BPM)';
COMMENT ON COLUMN RUN_RECORD.training_type_code IS '훈련 유형 코드 (LSD, INTERVAL 등)';
COMMENT ON COLUMN RUN_RECORD.rpe IS '운동 강도 (RPE 1~10)';
COMMENT ON COLUMN RUN_RECORD.temperature IS '기온 (온도)';
COMMENT ON COLUMN RUN_RECORD.humidity IS '습도 (%)';
COMMENT ON COLUMN RUN_RECORD.weather_code IS '기상 날씨 코드 (SUNNY, CLOUDY 등)';
COMMENT ON COLUMN RUN_RECORD.memo IS '기록 상세 메모';
COMMENT ON COLUMN RUN_RECORD.created_at IS '데이터 최초 생성 일시';
COMMENT ON COLUMN RUN_RECORD.updated_at IS '데이터 최종 수정 일시';

-- 4-6. GOAL Comments
COMMENT ON TABLE GOAL IS '러너의 연간/월간 목표 및 레이스 타겟';
COMMENT ON COLUMN GOAL.goal_id IS '목표 ID (PK)';
COMMENT ON COLUMN GOAL.runner_id IS '대상 러너 ID (FK)';
COMMENT ON COLUMN GOAL.goal_type_code IS '목표 유형 코드 (MONTH_DISTANCE 등)';
COMMENT ON COLUMN GOAL.goal_unit_code IS '목표 단위 코드 (KM, COUNT, TIME 등)';
COMMENT ON COLUMN GOAL.target_year IS '목표 타겟 년도';
COMMENT ON COLUMN GOAL.target_month IS '목표 타겟 월';
COMMENT ON COLUMN GOAL.target_value IS '설정 목표 수치';
COMMENT ON COLUMN GOAL.achieved_value IS '현재 도달한 실적 수치';
COMMENT ON COLUMN GOAL.start_date IS '목표 시작일';
COMMENT ON COLUMN GOAL.end_date IS '목표 종료일';
COMMENT ON COLUMN GOAL.created_at IS '목표 생성 일시';
COMMENT ON COLUMN GOAL.updated_at IS '목표 수정 일시';

-- 4-7. RACE_RECORD Comments
COMMENT ON TABLE RACE_RECORD IS '참가 마라톤 대회 기록 및 기록증 보관';
COMMENT ON COLUMN RACE_RECORD.race_record_id IS '대회 기록 ID (PK)';
COMMENT ON COLUMN RACE_RECORD.runner_id IS '참가 러너 ID (FK)';
COMMENT ON COLUMN RACE_RECORD.race_name IS '참가 대회 공식 명칭';
COMMENT ON COLUMN RACE_RECORD.race_date IS '대회 개최 일자';
COMMENT ON COLUMN RACE_RECORD.race_type_code IS '대회 코스 유형 코드 (RACE_FULL, RACE_HALF 등)';
COMMENT ON COLUMN RACE_RECORD.record_sec IS '완주 기록 (단위: 초)';
COMMENT ON COLUMN RACE_RECORD.certificate_image_url IS '공식 기록증 이미지 링크';
COMMENT ON COLUMN RACE_RECORD.memo IS '대회 참가 후기 및 메모';
COMMENT ON COLUMN RACE_RECORD.created_at IS '데이터 생성 일시';
COMMENT ON COLUMN RACE_RECORD.updated_at IS '데이터 수정 일시';


-- ==========================================
-- 5. SEED INITIAL COMMON CODES (초기 공통 코드 삽입)
-- ==========================================

-- 5-1. CODE_GROUP 데이터 삽입
INSERT INTO CODE_GROUP (group_code, group_name, description, use_yn) 
VALUES ('TRAINING_TYPE', '훈련 유형', '러닝 훈련의 성격 및 스타일 코드 그룹', 'Y');

INSERT INTO CODE_GROUP (group_code, group_name, description, use_yn) 
VALUES ('WEATHER_TYPE', '날씨 상태', '기상 및 기후 상태 코드 그룹', 'Y');

INSERT INTO CODE_GROUP (group_code, group_name, description, use_yn) 
VALUES ('GOAL_TYPE', '목표 유형', '월간 및 레이스 완주 목표 정의 코드 그룹', 'Y');

INSERT INTO CODE_GROUP (group_code, group_name, description, use_yn) 
VALUES ('RACE_TYPE', '대회 유형', '마라톤 대회의 공인 거리 분류 코드 그룹', 'Y');

INSERT INTO CODE_GROUP (group_code, group_name, description, use_yn) 
VALUES ('RUNNING_LEVEL', '러닝 레벨', '누적 거리에 따른 캐릭터 등급 구분 코드 그룹', 'Y');


-- 5-2. CODE_DETAIL 데이터 삽입

-- TRAINING_TYPE 상세
INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('TRAINING_TYPE', 'RECOVERY', '회복주', '피로 회복 목적 저강도 러닝', 1, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('TRAINING_TYPE', 'EASY', '이지런', '가벼운 조깅 및 편안한 페이스 주행', 2, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('TRAINING_TYPE', 'LSD', 'LSD', 'Long Slow Distance (장거리 심폐지구력 훈련)', 3, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('TRAINING_TYPE', 'TEMPO', '템포런', '정해진 페이스 유지 지속주 (젖산역치 훈련)', 4, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('TRAINING_TYPE', 'INTERVAL', '인터벌', '고강도 주행과 불완전 휴식을 반복하는 스피드 훈련', 5, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('TRAINING_TYPE', 'BUILDUP', '빌드업런', '점진적으로 속도를 증가시키는 훈련', 6, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('TRAINING_TYPE', 'RACE', '레이스', '공식 대회 참가 주행 데이터', 7, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('TRAINING_TYPE', 'OTHER', '기타', '기타 훈련 방식', 8, 'Y');


-- WEATHER_TYPE 상세
INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('WEATHER_TYPE', 'SUNNY', '맑음', '햇빛이 강하고 구름이 적은 맑은 날씨', 1, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('WEATHER_TYPE', 'CLOUDY', '흐림', '구름이 많은 날씨', 2, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('WEATHER_TYPE', 'RAIN', '비', '강수 상태', 3, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('WEATHER_TYPE', 'SNOW', '눈', '강설 상태', 4, 'Y');


-- GOAL_TYPE 상세
INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('GOAL_TYPE', 'MONTH_DISTANCE', '월간 목표 거리', '한 달 동안 누적 주행할 목표 거리(km)', 1, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('GOAL_TYPE', 'MONTH_RUN_COUNT', '월간 목표 운동 횟수', '한 달 동안 러닝을 수행할 목표 횟수', 2, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('GOAL_TYPE', 'RACE_5K', '5km 목표 기록', '5km 코스 목표 도달 시간', 3, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('GOAL_TYPE', 'RACE_10K', '10km 목표 기록', '10km 코스 목표 도달 시간', 4, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('GOAL_TYPE', 'RACE_HALF', '하프 목표 기록', '하프 마라톤 코스 목표 도달 시간', 5, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('GOAL_TYPE', 'RACE_FULL', '풀코스 목표 기록', '풀코스 마라톤 목표 도달 시간', 6, 'Y');


-- RACE_TYPE 상세
INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('RACE_TYPE', 'RACE_5K', '5km 코스', '5km 단거리 단축 마라톤', 1, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('RACE_TYPE', 'RACE_10K', '10km 코스', '10km 로드 레이스 단골 코스', 2, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('RACE_TYPE', 'RACE_HALF', '하프 코스', '하프 마라톤 (21.0975km)', 3, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('RACE_TYPE', 'RACE_FULL', '풀코스', '풀코스 마라톤 (42.195km)', 4, 'Y');


-- RUNNING_LEVEL 상세
INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('RUNNING_LEVEL', 'LV_CAT', '고양이 러너', '누적 거리 100km 미만의 비기너 등급', 1, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('RUNNING_LEVEL', 'LV_DEER', '사슴 러너', '누적 거리 100km 이상 300km 미만의 애호가 등급', 2, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('RUNNING_LEVEL', 'LV_WOLF', '늑대 러너', '누적 거리 300km 이상 600km 미만의 숙련자 등급', 3, 'Y');

INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES ('RUNNING_LEVEL', 'LV_CHEETAH', '치타 러너', '누적 거리 600km 이상의 최상위 러너 등급', 4, 'Y');

-- COMMIT CHANGES
COMMIT;
