-- =========================================================================
-- Project: Running Coach (러닝 코치)
-- Target DBMS: PostgreSQL 12 or higher (PostgreSQL 15/16 recommended)
-- Version: v3.0 (슬로우 러닝 & 부상 방지 헬스케어 맞춤형 스펙)
-- Description: PostgreSQL Database DDL & Initial Seed Script
-- Created Date: 2026-08-21
-- Writer: Running Coach Architecture Team
-- =========================================================================

BEGIN;

-- ==========================================
-- 0. DROP TABLES (CASCADE)
-- ==========================================
DROP TABLE IF EXISTS GARMIN_RUN_LAP CASCADE;
DROP TABLE IF EXISTS GARMIN_RUN_DETAIL CASCADE;
DROP TABLE IF EXISTS RUN_RECORD CASCADE;
DROP TABLE IF EXISTS RUNNING_SHOES CASCADE;
DROP TABLE IF EXISTS GARMIN_ACCOUNT_LINK CASCADE;
DROP TABLE IF EXISTS RUNNER_SOCIAL_ACCOUNT CASCADE;
DROP TABLE IF EXISTS RUNNER CASCADE;
DROP TABLE IF EXISTS CODE_DETAIL CASCADE;
DROP TABLE IF EXISTS CODE_GROUP CASCADE;

-- ==========================================
-- 1. CREATE TABLES & PRIMARY KEYS
-- ==========================================

-- 1-1. CODE_GROUP (코드 그룹)
CREATE TABLE CODE_GROUP (
    group_code  VARCHAR(30) NOT NULL,
    group_name  VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    use_yn      CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP,
    CONSTRAINT PK_CODE_GROUP PRIMARY KEY (group_code),
    CONSTRAINT CK_CODE_GROUP_USE_YN CHECK (use_yn IN ('Y', 'N'))
);

-- 1-2. CODE_DETAIL (코드 상세)
CREATE TABLE CODE_DETAIL (
    code_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_code  VARCHAR(30) NOT NULL,
    code_value  VARCHAR(30) NOT NULL,
    code_name   VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    sort_order  INTEGER,
    use_yn      CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP,
    CONSTRAINT PK_CODE_DETAIL PRIMARY KEY (code_id),
    CONSTRAINT CK_CODE_DETAIL_USE_YN CHECK (use_yn IN ('Y', 'N'))
);

-- 1-3. RUNNER (러너 정보)
CREATE TABLE RUNNER (
    runner_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nickname           VARCHAR(50),
    profile_image_url  VARCHAR(500),
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP,
    CONSTRAINT PK_RUNNER PRIMARY KEY (runner_id)
);

-- 1-4. RUNNER_SOCIAL_ACCOUNT (소셜 로그인 정보)
CREATE TABLE RUNNER_SOCIAL_ACCOUNT (
    social_account_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    runner_id         BIGINT NOT NULL,
    provider          VARCHAR(20) NOT NULL,
    provider_user_id  VARCHAR(100) NOT NULL,
    provider_email    VARCHAR(200),
    is_primary        CHAR(1) DEFAULT 'N' NOT NULL,
    connected_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_login_at     TIMESTAMP,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP,
    CONSTRAINT PK_RUNNER_SOCIAL_ACCOUNT PRIMARY KEY (social_account_id),
    CONSTRAINT CK_SOCIAL_IS_PRIMARY CHECK (is_primary IN ('Y', 'N'))
);

-- 1-4-2. GARMIN_ACCOUNT_LINK (가민 계정 연동 및 동기화 정보)
CREATE TABLE GARMIN_ACCOUNT_LINK (
    garmin_link_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    runner_id               BIGINT NOT NULL,
    garmin_email            VARCHAR(100) NOT NULL,
    token_store_path        VARCHAR(255),
    is_connected            BOOLEAN DEFAULT TRUE NOT NULL,
    initial_sync_completed  BOOLEAN DEFAULT FALSE NOT NULL,
    last_synced_at          TIMESTAMP,
    created_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at              TIMESTAMP,
    CONSTRAINT PK_GARMIN_ACCOUNT_LINK PRIMARY KEY (garmin_link_id),
    CONSTRAINT UQ_GARMIN_LINK_RUNNER_ID UNIQUE (runner_id)
);

-- 1-4-3. RUNNING_SHOES (러닝화 관리 - 수명 및 누적거리 트래킹)
CREATE TABLE RUNNING_SHOES (
    shoe_id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    runner_id            BIGINT NOT NULL,
    shoe_name            VARCHAR(100) NOT NULL,
    brand                VARCHAR(50),
    max_distance_km      NUMERIC(6,2) DEFAULT 600.00 NOT NULL, -- 러닝화 목표 수명 (기본 600km)
    current_distance_km  NUMERIC(6,2) DEFAULT 0.00 NOT NULL,   -- 누적 주행 거리
    is_default           BOOLEAN DEFAULT FALSE NOT NULL,
    is_retired           BOOLEAN DEFAULT FALSE NOT NULL,
    purchased_date       DATE,
    created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at           TIMESTAMP,
    CONSTRAINT PK_RUNNING_SHOES PRIMARY KEY (shoe_id)
);

-- 1-5. RUN_RECORD (러닝 기록 - 슬로우 러닝 및 부상 방지 스펙 적용)
CREATE TABLE RUN_RECORD (
    run_record_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    runner_id          BIGINT NOT NULL,
    shoe_id            BIGINT, -- 착용한 러닝화 FK
    run_datetime       TIMESTAMP NOT NULL,
    run_date           DATE NOT NULL,
    duration_sec       INTEGER NOT NULL,
    distance_km        NUMERIC(6,2) NOT NULL,
    avg_pace_sec       INTEGER,
    avg_hr             INTEGER,
    max_hr             INTEGER, -- 주행 중 최고/최대 심박수 (BPM)
    condition_score    INTEGER DEFAULT 2, -- 1: 무거움, 2: 보통, 3: 상쾌함
    pain_area_code     VARCHAR(30) DEFAULT 'NONE', -- 통증 부위 코드
    pain_level         INTEGER DEFAULT 0, -- 0: 없음, 1: 뻐근함, 2: 불편함, 3: 심함
    temperature        NUMERIC(4,1),
    humidity           INTEGER,
    weather_code       VARCHAR(30),
    memo               VARCHAR(1000),
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP,
    CONSTRAINT PK_RUN_RECORD PRIMARY KEY (run_record_id),
    CONSTRAINT CK_RUN_CONDITION CHECK (condition_score BETWEEN 1 AND 3),
    CONSTRAINT CK_RUN_PAIN_LEVEL CHECK (pain_level BETWEEN 0 AND 3),
    CONSTRAINT CK_RUN_DISTANCE CHECK (distance_km > 0),
    CONSTRAINT CK_RUN_DURATION CHECK (duration_sec > 0),
    CONSTRAINT CK_RUN_HR CHECK (avg_hr IS NULL OR avg_hr BETWEEN 30 AND 250),
    CONSTRAINT CK_RUN_MAX_HR CHECK (max_hr IS NULL OR (max_hr BETWEEN 30 AND 250 AND (avg_hr IS NULL OR max_hr >= avg_hr)))
);

-- 1-6. GARMIN_RUN_DETAIL (가민 정밀 분석 상세 - 1:1)
CREATE TABLE GARMIN_RUN_DETAIL (
    garmin_detail_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    run_record_id             BIGINT NOT NULL,
    garmin_activity_id        BIGINT NOT NULL,
    max_hr                    INTEGER,
    avg_cadence               INTEGER,
    max_cadence               INTEGER,
    avg_stride_length_mm      INTEGER,
    elevation_gain_m          NUMERIC(6,1),
    elevation_loss_m          NUMERIC(6,1),
    vo2_max                   NUMERIC(4,1),
    training_effect_aerobic   NUMERIC(3,1),
    training_effect_anaerobic NUMERIC(3,1),
    calories                  INTEGER,
    gpx_route_json            JSONB,
    created_at                TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at                TIMESTAMP,
    CONSTRAINT PK_GARMIN_RUN_DETAIL PRIMARY KEY (garmin_detail_id),
    CONSTRAINT UQ_GARMIN_ACTIVITY_ID UNIQUE (garmin_activity_id),
    CONSTRAINT UQ_GARMIN_RUN_RECORD_ID UNIQUE (run_record_id)
);

-- 1-7. GARMIN_RUN_LAP (가민 km별 구간 랩 타임 - 1:N)
CREATE TABLE GARMIN_RUN_LAP (
    lap_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    run_record_id    BIGINT NOT NULL,
    lap_index        INTEGER NOT NULL,
    lap_distance_km  NUMERIC(5,2) NOT NULL,
    lap_duration_sec INTEGER NOT NULL,
    lap_avg_pace_sec INTEGER,
    lap_avg_hr       INTEGER,
    lap_max_hr       INTEGER,
    lap_avg_cadence  INTEGER,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_GARMIN_RUN_LAP PRIMARY KEY (lap_id)
);

-- ==========================================
-- 2. CREATE INDEXES
-- ==========================================

-- 2-1. RUNNER_SOCIAL_ACCOUNT Indexes
CREATE UNIQUE INDEX UIDX_RUNNER_SOCIAL_ACCOUNT_01 ON RUNNER_SOCIAL_ACCOUNT(provider, provider_user_id);
CREATE INDEX IDX_RUNNER_SOCIAL_ACCOUNT_01 ON RUNNER_SOCIAL_ACCOUNT(runner_id);

-- 2-1-2. GARMIN_ACCOUNT_LINK Indexes
CREATE INDEX IDX_GARMIN_LINK_01 ON GARMIN_ACCOUNT_LINK(is_connected, last_synced_at);

-- 2-2. RUN_RECORD Indexes
CREATE INDEX IDX_RUN_RECORD_01 ON RUN_RECORD(runner_id, run_date);
CREATE INDEX IDX_RUN_RECORD_02 ON RUN_RECORD(runner_id, pain_area_code);
CREATE INDEX IDX_RUN_RECORD_03 ON RUN_RECORD(run_date);
CREATE INDEX IDX_RUN_RECORD_04 ON RUN_RECORD(runner_id, run_datetime);

-- 2-3. CODE_DETAIL Indexes
CREATE UNIQUE INDEX UIDX_CODE_DETAIL_01 ON CODE_DETAIL(group_code, code_value);
CREATE INDEX IDX_CODE_DETAIL_02 ON CODE_DETAIL(group_code);

-- 2-4. GARMIN_RUN_DETAIL & GARMIN_RUN_LAP Indexes
CREATE UNIQUE INDEX UIDX_GARMIN_RUN_DETAIL_01 ON GARMIN_RUN_DETAIL(garmin_activity_id);
CREATE UNIQUE INDEX UIDX_GARMIN_RUN_DETAIL_02 ON GARMIN_RUN_DETAIL(run_record_id);
CREATE INDEX IDX_GARMIN_RUN_LAP_01 ON GARMIN_RUN_LAP(run_record_id, lap_index);

CREATE INDEX IDX_RUNNING_SHOES_01 ON RUNNING_SHOES(runner_id, is_retired);
CREATE INDEX IDX_RUN_RECORD_05 ON RUN_RECORD(shoe_id);
-- ==========================================
-- 3. CREATE UNIQUE & FOREIGN KEY CONSTRAINTS
-- ==========================================

ALTER TABLE RUNNER_SOCIAL_ACCOUNT ADD CONSTRAINT UQ_SOCIAL_PROVIDER_USER UNIQUE USING INDEX UIDX_RUNNER_SOCIAL_ACCOUNT_01;
ALTER TABLE CODE_DETAIL ADD CONSTRAINT UQ_CODE_DETAIL_VAL UNIQUE USING INDEX UIDX_CODE_DETAIL_01;

ALTER TABLE CODE_DETAIL ADD CONSTRAINT FK_CODE_DETAIL_GROUP FOREIGN KEY (group_code) REFERENCES CODE_GROUP(group_code) ON DELETE CASCADE;
ALTER TABLE RUNNER_SOCIAL_ACCOUNT ADD CONSTRAINT FK_SOCIAL_RUNNER FOREIGN KEY (runner_id) REFERENCES RUNNER(runner_id) ON DELETE CASCADE;
ALTER TABLE GARMIN_ACCOUNT_LINK ADD CONSTRAINT FK_GARMIN_LINK_RUNNER FOREIGN KEY (runner_id) REFERENCES RUNNER(runner_id) ON DELETE CASCADE;
ALTER TABLE RUNNING_SHOES ADD CONSTRAINT FK_SHOES_RUNNER FOREIGN KEY (runner_id) REFERENCES RUNNER(runner_id) ON DELETE CASCADE;
ALTER TABLE RUN_RECORD ADD CONSTRAINT FK_RUN_RECORD_RUNNER FOREIGN KEY (runner_id) REFERENCES RUNNER(runner_id) ON DELETE CASCADE;
ALTER TABLE RUN_RECORD ADD CONSTRAINT FK_RUN_RECORD_SHOE FOREIGN KEY (shoe_id) REFERENCES RUNNING_SHOES(shoe_id) ON DELETE SET NULL;
ALTER TABLE GARMIN_RUN_DETAIL ADD CONSTRAINT FK_GARMIN_DETAIL_RUN_RECORD FOREIGN KEY (run_record_id) REFERENCES RUN_RECORD(run_record_id) ON DELETE CASCADE;
ALTER TABLE GARMIN_RUN_LAP ADD CONSTRAINT FK_GARMIN_LAP_RUN_RECORD FOREIGN KEY (run_record_id) REFERENCES RUN_RECORD(run_record_id) ON DELETE CASCADE;

-- ==========================================
-- 4. SCHEMA COMMENTS
-- ==========================================

COMMENT ON TABLE CODE_GROUP IS '공통 코드 그룹 테이블';
COMMENT ON TABLE CODE_DETAIL IS '공통 코드 상세 매핑 테이블';
COMMENT ON TABLE RUNNER IS '러너 기본 정보 테이블';
COMMENT ON TABLE RUNNER_SOCIAL_ACCOUNT IS '소셜 연동 다중 계정 정보';
COMMENT ON TABLE GARMIN_ACCOUNT_LINK IS '가민 계정 연동 및 동기화 상태 관리';
COMMENT ON TABLE RUN_RECORD IS '슬로우 러닝 & 부상 방지 러닝 기록 데이터';
COMMENT ON TABLE GARMIN_RUN_DETAIL IS '가민 정밀 분석 지표 데이터 (1:1)';
COMMENT ON TABLE GARMIN_RUN_LAP IS '가민 km/구간별 랩 타임 데이터 (1:N)';

-- ==========================================
-- 5. SEED INITIAL COMMON CODES
-- ==========================================

INSERT INTO CODE_GROUP (group_code, group_name, description, use_yn) 
VALUES ('PAIN_AREA', '통증 부위', '러닝 후 뻐근함이나 통증이 느껴진 인체 부위 코드 그룹', 'Y');

INSERT INTO CODE_GROUP (group_code, group_name, description, use_yn) 
VALUES ('WEATHER_TYPE', '날씨 상태', '기상 상태 코드 그룹', 'Y');

INSERT INTO CODE_GROUP (group_code, group_name, description, use_yn) 
VALUES ('RUNNING_LEVEL', '러닝 레벨', '누적 거리에 따른 캐릭터 등급 구분 코드 그룹', 'Y');

INSERT INTO CODE_GROUP (group_code, group_name, description, use_yn) 
VALUES ('RUNNING_LOCATION', '러닝 지역 권역', '수동 입력용 대표 러닝 지역 좌표 그룹', 'Y');

-- PAIN_AREA 상세
INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES 
('PAIN_AREA', 'NONE', '없음', '통증 없음 (정상)', 1, 'Y'),
('PAIN_AREA', 'KNEE_LEFT', '왼쪽 무릎', '왼쪽 슬관절 통증 및 뻐근함', 2, 'Y'),
('PAIN_AREA', 'KNEE_RIGHT', '오른쪽 무릎', '오른쪽 슬관절 통증 및 뻐근함', 3, 'Y'),
('PAIN_AREA', 'ANKLE', '발목', '발목 관절 통증', 4, 'Y'),
('PAIN_AREA', 'FOOT_SOLE', '발바닥(족저)', '족저근막 부위 통증', 5, 'Y'),
('PAIN_AREA', 'SHIN', '정강이(신스플린트)', '정강이 뼈 부위 통증', 6, 'Y'),
('PAIN_AREA', 'ACHILLES', '아킬레스건', '아킬레스건 부위 통증', 7, 'Y'),
('PAIN_AREA', 'HIP_THIGH', '고관절/허벅지', '고관절 및 햄스트링/대퇴사두 통증', 8, 'Y');

-- WEATHER_TYPE 상세
INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES 
('WEATHER_TYPE', 'SUNNY', '맑음', '맑은 날씨', 1, 'Y'),
('WEATHER_TYPE', 'CLOUDY', '흐림', '구름 많은 날씨', 2, 'Y'),
('WEATHER_TYPE', 'RAIN', '비', '강수 상태', 3, 'Y'),
('WEATHER_TYPE', 'SNOW', '눈', '강설 상태', 4, 'Y');

-- RUNNING_LEVEL 상세
INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES 
('RUNNING_LEVEL', 'LV_CAT', '고양이 러너', '누적 거리 100km 미만', 1, 'Y'),
('RUNNING_LEVEL', 'LV_DEER', '사슴 러너', '누적 거리 100km~300km', 2, 'Y'),
('RUNNING_LEVEL', 'LV_WOLF', '늑대 러너', '누적 거리 300km~600km', 3, 'Y'),
('RUNNING_LEVEL', 'LV_CHEETAH', '치타 러너', '누적 거리 600km 이상', 4, 'Y');

-- RUNNING_LOCATION 상세
INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES 
('RUNNING_LOCATION', 'SEOUL_METRO', '서울/수도권 북부', '37.5665,126.9780', 1, 'Y'),
('RUNNING_LOCATION', 'GYEONGGI_SOUTH', '수도권 남부 (성남/수원/용인)', '37.3827,127.1189', 2, 'Y'),
('RUNNING_LOCATION', 'INCHEON_WEST', '인천/수도권 서부', '37.4563,126.7052', 3, 'Y'),
('RUNNING_LOCATION', 'GANGWON', '강원권 (춘천/원주/강릉)', '37.7519,128.8761', 4, 'Y'),
('RUNNING_LOCATION', 'CHUNGCHEONG', '대전/충청권', '36.3504,127.3845', 5, 'Y'),
('RUNNING_LOCATION', 'GYEONGBUK', '대구/경북권', '35.8714,128.6014', 6, 'Y'),
('RUNNING_LOCATION', 'GYEONGNAM', '부산/울산/경남권', '35.1796,129.0756', 7, 'Y'),
('RUNNING_LOCATION', 'JEONLA', '광주/전라권', '35.1595,126.8526', 8, 'Y'),
('RUNNING_LOCATION', 'JEJU', '제주도', '33.4996,126.5312', 9, 'Y'),
('RUNNING_LOCATION', 'OTHER', '해외/기타', '37.5665,126.9780', 10, 'Y');

COMMIT;
