-- =========================================================================
-- Project: Running Coach (러닝 코치)
-- Target DBMS: PostgreSQL 12 or higher (PostgreSQL 15/16 recommended)
-- Version: v2.0 (1차 MVP - 대시보드/러닝기록/조회/통계 분석 경량화 버전)
-- Description: PostgreSQL Database DDL & Initial Seed Script
-- Created Date: 2026-08-04
-- Writer: Running Coach Architecture Team
-- =========================================================================

BEGIN;

-- ==========================================
-- 0. DROP TABLES (CASCADE)
-- ==========================================
DROP TABLE IF EXISTS RUN_RECORD CASCADE;
DROP TABLE IF EXISTS RUNNER_SOCIAL_ACCOUNT CASCADE;
DROP TABLE IF EXISTS RUNNER CASCADE;
DROP TABLE IF EXISTS CODE_DETAIL CASCADE;
DROP TABLE IF EXISTS CODE_GROUP CASCADE;

-- ==========================================
-- 1. CREATE TABLES & PRIMARY KEYS
-- ==========================================

-- 1-1. CODE_GROUP (코드 그룹)
CREATE TABLE CODE_GROUP (
    group_code  VARCHAR(30) NOT NULL,
    group_name  VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    use_yn      CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP,
    CONSTRAINT PK_CODE_GROUP PRIMARY KEY (group_code),
    CONSTRAINT CK_CODE_GROUP_USE_YN CHECK (use_yn IN ('Y', 'N'))
);

-- 1-2. CODE_DETAIL (코드 상세)
CREATE TABLE CODE_DETAIL (
    code_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_code  VARCHAR(30) NOT NULL,
    code_value  VARCHAR(30) NOT NULL,
    code_name   VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    sort_order  INTEGER,
    use_yn      CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP,
    CONSTRAINT PK_CODE_DETAIL PRIMARY KEY (code_id),
    CONSTRAINT CK_CODE_DETAIL_USE_YN CHECK (use_yn IN ('Y', 'N'))
);

-- 1-3. RUNNER (러너 정보)
CREATE TABLE RUNNER (
    runner_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nickname           VARCHAR(50),
    profile_image_url  VARCHAR(500),
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP,
    CONSTRAINT PK_RUNNER PRIMARY KEY (runner_id)
);

-- 1-4. RUNNER_SOCIAL_ACCOUNT (소셜 로그인 정보)
CREATE TABLE RUNNER_SOCIAL_ACCOUNT (
    social_account_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    runner_id         BIGINT NOT NULL,
    provider          VARCHAR(20) NOT NULL,
    provider_user_id  VARCHAR(100) NOT NULL,
    provider_email    VARCHAR(200),
    is_primary        CHAR(1) DEFAULT 'N' NOT NULL,
    connected_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_login_at     TIMESTAMP,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP,
    CONSTRAINT PK_RUNNER_SOCIAL_ACCOUNT PRIMARY KEY (social_account_id),
    CONSTRAINT CK_SOCIAL_IS_PRIMARY CHECK (is_primary IN ('Y', 'N'))
);

-- 1-5. RUN_RECORD (러닝 기록)
CREATE TABLE RUN_RECORD (
    run_record_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    runner_id          BIGINT NOT NULL,
    run_datetime       TIMESTAMP NOT NULL,
    run_date           DATE NOT NULL,
    duration_sec       INTEGER NOT NULL,
    distance_km        NUMERIC(6,2) NOT NULL,
    avg_pace_sec       INTEGER,
    avg_hr             INTEGER,
    training_type_code VARCHAR(30) NOT NULL,
    rpe                INTEGER,
    temperature        NUMERIC(4,1),
    humidity           INTEGER,
    weather_code       VARCHAR(30),
    memo               VARCHAR(1000),
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP,
    CONSTRAINT PK_RUN_RECORD PRIMARY KEY (run_record_id),
    CONSTRAINT CK_RUN_RECORD_RPE CHECK (rpe BETWEEN 1 AND 10),
    CONSTRAINT CK_RUN_DISTANCE CHECK (distance_km > 0),
    CONSTRAINT CK_RUN_DURATION CHECK (duration_sec > 0),
    CONSTRAINT CK_RUN_HR CHECK (avg_hr IS NULL OR avg_hr BETWEEN 30 AND 250)
);

-- ==========================================
-- 2. CREATE INDEXES
-- ==========================================

-- 2-1. RUNNER_SOCIAL_ACCOUNT Indexes
CREATE UNIQUE INDEX UIDX_RUNNER_SOCIAL_ACCOUNT_01 ON RUNNER_SOCIAL_ACCOUNT(provider, provider_user_id);
CREATE INDEX IDX_RUNNER_SOCIAL_ACCOUNT_01 ON RUNNER_SOCIAL_ACCOUNT(runner_id);

-- 2-2. RUN_RECORD Indexes
CREATE INDEX IDX_RUN_RECORD_01 ON RUN_RECORD(runner_id, run_date);
CREATE INDEX IDX_RUN_RECORD_02 ON RUN_RECORD(runner_id, training_type_code);
CREATE INDEX IDX_RUN_RECORD_03 ON RUN_RECORD(run_date);
CREATE INDEX IDX_RUN_RECORD_04 ON RUN_RECORD(runner_id, run_datetime);

-- 2-3. CODE_DETAIL Indexes
CREATE UNIQUE INDEX UIDX_CODE_DETAIL_01 ON CODE_DETAIL(group_code, code_value);
CREATE INDEX IDX_CODE_DETAIL_02 ON CODE_DETAIL(group_code);

-- ==========================================
-- 3. CREATE UNIQUE & FOREIGN KEY CONSTRAINTS
-- ==========================================

ALTER TABLE RUNNER_SOCIAL_ACCOUNT ADD CONSTRAINT UQ_SOCIAL_PROVIDER_USER UNIQUE USING INDEX UIDX_RUNNER_SOCIAL_ACCOUNT_01;
ALTER TABLE CODE_DETAIL ADD CONSTRAINT UQ_CODE_DETAIL_VAL UNIQUE USING INDEX UIDX_CODE_DETAIL_01;

ALTER TABLE CODE_DETAIL ADD CONSTRAINT FK_CODE_DETAIL_GROUP FOREIGN KEY (group_code) REFERENCES CODE_GROUP(group_code) ON DELETE CASCADE;
ALTER TABLE RUNNER_SOCIAL_ACCOUNT ADD CONSTRAINT FK_SOCIAL_RUNNER FOREIGN KEY (runner_id) REFERENCES RUNNER(runner_id) ON DELETE CASCADE;
ALTER TABLE RUN_RECORD ADD CONSTRAINT FK_RUN_RECORD_RUNNER FOREIGN KEY (runner_id) REFERENCES RUNNER(runner_id) ON DELETE CASCADE;

-- ==========================================
-- 4. SCHEMA COMMENTS
-- ==========================================

COMMENT ON TABLE CODE_GROUP IS '공통 코드 그룹 테이블';
COMMENT ON TABLE CODE_DETAIL IS '공통 코드 상세 매핑 테이블';
COMMENT ON TABLE RUNNER IS '러너 기본 정보 테이블';
COMMENT ON TABLE RUNNER_SOCIAL_ACCOUNT IS '소셜 연동 다중 계정 정보';
COMMENT ON TABLE RUN_RECORD IS '러닝 기록 세부 데이터';

-- ==========================================
-- 5. SEED INITIAL COMMON CODES
-- ==========================================

INSERT INTO CODE_GROUP (group_code, group_name, description, use_yn) 
VALUES ('TRAINING_TYPE', '훈련 유형', '러닝 훈련 성격 코드 그룹', 'Y');

INSERT INTO CODE_GROUP (group_code, group_name, description, use_yn) 
VALUES ('WEATHER_TYPE', '날씨 상태', '기상 상태 코드 그룹', 'Y');

INSERT INTO CODE_GROUP (group_code, group_name, description, use_yn) 
VALUES ('RUNNING_LEVEL', '러닝 레벨', '누적 거리에 따른 캐릭터 등급 구분 코드 그룹', 'Y');

-- TRAINING_TYPE 상세
INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES 
('TRAINING_TYPE', 'RECOVERY', '회복주', '피로 회복 목적 저강도 러닝', 1, 'Y'),
('TRAINING_TYPE', 'EASY', '이지런', '가벼운 조깅 및 편안한 페이스 주행', 2, 'Y'),
('TRAINING_TYPE', 'LSD', 'LSD', 'Long Slow Distance', 3, 'Y'),
('TRAINING_TYPE', 'TEMPO', '템포런', '정해진 페이스 유지 지속주', 4, 'Y'),
('TRAINING_TYPE', 'INTERVAL', '인터벌', '고강도 스피드 훈련', 5, 'Y'),
('TRAINING_TYPE', 'BUILDUP', '빌드업런', '점진적 속도 증가 훈련', 6, 'Y'),
('TRAINING_TYPE', 'RACE', '레이스', '공식 대회 참가 주행', 7, 'Y'),
('TRAINING_TYPE', 'OTHER', '기타', '기타 훈련 방식', 8, 'Y');

-- WEATHER_TYPE 상세
INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES 
('WEATHER_TYPE', 'SUNNY', '맑음', '맑은 날씨', 1, 'Y'),
('WEATHER_TYPE', 'CLOUDY', '흐림', '구름 많은 날씨', 2, 'Y'),
('WEATHER_TYPE', 'RAIN', '비', '강수 상태', 3, 'Y'),
('WEATHER_TYPE', 'SNOW', '눈', '강설 상태', 4, 'Y');

-- RUNNING_LEVEL 상세
INSERT INTO CODE_DETAIL (group_code, code_value, code_name, description, sort_order, use_yn)
VALUES 
('RUNNING_LEVEL', 'LV_CAT', '고양이 러너', '누적 거리 100km 미만', 1, 'Y'),
('RUNNING_LEVEL', 'LV_DEER', '사슴 러너', '누적 거리 100km~300km', 2, 'Y'),
('RUNNING_LEVEL', 'LV_WOLF', '늑대 러너', '누적 거리 300km~600km', 3, 'Y'),
('RUNNING_LEVEL', 'LV_CHEETAH', '치타 러너', '누적 거리 600km 이상', 4, 'Y');

COMMIT;
