server:
  port: 8080

spring:
  application:
    name: running-coach-core

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/runner_db
    username: runner_user
    password: runner_password

mybatis:
  type-aliases-package: com.runner.core.domain
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
